ansible_become_pass: ENC[AES256_GCM,data:tW57bn2xKGz+rZJI,iv:PC6tT6Z1CmhwS+24W8SJqeIf5oUZmVx6bYRuR4tbmNg=,tag:W5irRjo5SY/gjp6JK90s1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l7f2np2gjaga5zusg7tltae997ft8ha4zglm5qftn3snx8xyefrscdxg7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOE1GR1JKak84bkdBdm5P
            dHZjUlZ1RlZQNnNQMzhwditVRlFVK3cyRzMwCmNkYUZsS2NGYnRLb2xYbnhTNjNR
            ZTBhS2lrdk90eEpwaHVSdnAyNkR0MEEKLS0tIE1aNklZRng2U2NTQ052NzZudG9P
            blRCOGhJM0JMOTljR2JFQ1dEVE5ZTzAKDkoXKRfs8d7SL024cjav1Qjcf14XYKsi
            7TTpZuxyJ1m3PnVXOyAOaacqhFeGFVkejE6jUa+IrzJM/eV00BdHMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T11:47:00Z"
    mac: ENC[AES256_GCM,data:5pNByLRFUH2NeoYLDRIj8SFvipkGpz3tDNgq4v9oIMboWcy/AhdXURGEl2a7yog8k0El33CaPz0QFIuAib5iGWzbNkpBF25uNOPpyHWPopKAzdBgkoxJmXcJSX/VmbcXYJnFZKXbDpBLCJ/dxOE0eVOglJNadtlaK1LOYdEDVac=,iv:6GL9STpe0HYMBR02YcNzebGR4LAGvR9XMlFyzSTsll0=,tag:f2m1e8VxFuRGSx97FXHflQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
