apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:HggUhL0yIWiXXNbetSFgUV9ZcGC3Ezzr,iv:ESbd+PlqLvDSn2z9PBt0z5KgNInxJwb2N9aC2Q1DtbE=,tag:zGnvMmj1iePb3PaziZ+q6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l7f2np2gjaga5zusg7tltae997ft8ha4zglm5qftn3snx8xyefrscdxg7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaa3dlTnJsMGlwSy9wbWZo
            T050dXVZN2lzelBXc3QrS0o3dGhRVlNFekI4CnVDWm1YWU9OcEpPNzhBUmIzTm5a
            enhiUW0xWFgwWkJHczdtN2ZPTnYwM1EKLS0tIFIxVVkzaW5VRlJpL21Kc2J0d3A2
            RUMzNFl0TVlyMVBrQTJOWm9ZZDE2encKVnoWmHgDzN4XBl0LjMyvmQipRv4mmxHW
            CHBAAGDHtLKqxIij0eJ4ZuX3Lz5iBS71l6EvfYX78CeUd0A82fNGug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T13:08:06Z"
    mac: ENC[AES256_GCM,data:GNUKbSsroL8s3Q0SKv+hiyp1pzYisYrTdc6/Fp2ywQBmmKIjez6Oekuw2hBzVkokJA2hN/30s9Fp3MzFPmSaFzfARA2iCraBmbSA33PvElH7eN991T00gLjSa2wmqkSy9qTAj887dLHr/hYy+6woGFWsDv8GPEJPOKJpP+AIDfM=,iv:NlJeCEoQurfSSaXsaOwaycLpJvIMmtzLY6zPNeHZsDg=,tag:mqS2k1i+9ZZtSlswgekzxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
