apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:7MtoCmxXT5fCfeGgav0vM1Dtly5UftXW1gOyY54AlrCdzN401tDOHA==,iv:QlEelpjKeL2CYE0GBHnKBLj2Bt/qrFAR1dbOXkagl0s=,tag:SbEAvAScwJlL52dN8i9oxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l7f2np2gjaga5zusg7tltae997ft8ha4zglm5qftn3snx8xyefrscdxg7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeGJCbHR0UmRzbC9TZVdO
            K1ZuT2cxY3pZeVlxcXJUR1NBNkxNZE4rYVE4CnlTNmM1RXFlaEZPU2IwdVhEWmlU
            Qlo1VmlZT1pFWGJnbnZMNkNjQlJZaVkKLS0tIGV1Q3I3QitxbnNFOUd0dDMvY05Z
            NVdabHpKSUhneU5lSFNRVHhBYklJQTgK0RAzoPzUwJZd9L6845IcrU62AVDmCaQp
            eSehB91yj5Y9k+RvtkHYpKqpeSZtY6q2LRqxm2igEGvDja7lp+HOSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T11:47:34Z"
    mac: ENC[AES256_GCM,data:grsL8lzIu2pfN8HPI1q9bm4wRf2xfg1aOPhstc4UzV61rcA+o7wk/ZbE+kkrdmYlOdusAavDJxFtRms2FC91I2cyn4IRpi7fEOI61yqujhnUZyiR4YvK7jW1qH9QUdbHTU1JwCRbVCpKVxhNOicn0lcfor+bHgRUAjf+F9JDecs=,iv:tK7qLbHkH6Ey8qSg2gnRnXmGuJ5iJ6pLjNmH+25rcQs=,tag:THrMxHyv1UFEQxADVbMWSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
