apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:mzZWPRYDYFyCICv4,iv:bCU13lCQKVKroFn6jwCvXtQHg080uTi9NuniP0MjdFs=,tag:XrBvF0zNWgqd8nJI5WgMpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l7f2np2gjaga5zusg7tltae997ft8ha4zglm5qftn3snx8xyefrscdxg7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBejlKNEsvZCtIOHVzVnhJ
            OTRkdVVDMVlsdE9LU2JKOVhScXRpbFVzeWlnCjJjakx6VlpTWXdsM3lCNmV1Mk5n
            Z2JiZ0xnenNCa1pRSmhJanhZYkd5UmMKLS0tIDBBdUFmOTZReEdsL1lYUmNEdDF1
            c3BERnN1dXhDVmFCR0o5N2NIcVBYbzQKg1kCx0Q6uiwD5RJD7Uu2evlaw2LykkGb
            gNcNzf4ZTdG1qErkhOC6T2FjyhpEivmPlMFEAin+srnNUoX2fJoVZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T11:47:33Z"
    mac: ENC[AES256_GCM,data:DnUUhC5h732gNW8ImLyg6+sQotN1lsHgQSgY2fnzVxv0xN/snxFFIL44C7hASNXrglMPg85NwGZVkgF8kbOYKd/3SqFmwK3UXPrFLZCScXdKX5Hue2B3luUDIaGBnTqQP4kLMQMyg4pM4aFkryDQr2CrhOLiUYFQ5kBkvOZRoR8=,iv:pezJ6zorRrSEgY5Fcoc+c3fSnhWuzTFSDKLXXfAqjug=,tag:egLH3lXSuEL55LdxN+azmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
