apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:e8Jx0ssepSTgkJC2wKtFxF31B1LMTdTIRulu+xJED/lSSRxO,iv:24BbTSmCcwWO/DXm7SN2rHoZPDYiiEGRkFRxCnpvqV4=,tag:MhOp998PaBkvodU7KEB01A==,type:str]
    credentials.json: ENC[AES256_GCM,data:FIHPc2V2Hbtzn3riMGWRt/YtgJUCsHZteAZNGOyiyIRFxEuhlo41Uf88NZSdZI3DNVIpwVEMJxEBIqIcSP7evuQaxdsMdkxJiWqcqWXMOJGZXIAsYdi0muGwTjVUqsOp9ZQd5Ly58U109TAefHzqxfTdo7FNP7ReJG92tzUWt9kCEorjz4ffTwxuWZufNmx/G2Xg13uxewaH8K7xvevNOjk8UKZtP7OgmgK63U3fWw==,iv:g35P9O5aj9W/lSt2Wb+oRtbZQ5JbZtg84X4THqIpFUk=,tag:AUQKTnUld/I4p0cREpjkXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l7f2np2gjaga5zusg7tltae997ft8ha4zglm5qftn3snx8xyefrscdxg7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRWxjdURKdzR4UHQ2QmRC
            VTE0c2FxRjRsaSt4Z2V0SXlaZUFHdkplYjNvClpsa0RDUUxUSUZ4UXpLRlJyTGtT
            ck8vMW5PRlFTNFhBSEF5WUtLSG0yT28KLS0tIFQwNG5kTmVKL0w0RzFSVXBQOVpV
            di9lVUp5YUg1aVhWZDdVNHFET0hQMDAKmiHYq68k8QiSP/MnM1tnmhuSBlIkB5oj
            Lc7MS5YYOZHjSHzbYcBNoaeCxLnSo+wuCRnzLE0El73eK7NfK8u+Ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T13:08:07Z"
    mac: ENC[AES256_GCM,data:VfwB7xtP7uSESUJsU42HpfPwmQ209cxkY7uVgHzGsjm4J2hLaoYB6Rwq9lagZpGCMIRKsQtFU67WwKdWhG1uFjIGZHWsvnwDY9M3ipfO6AqhvzGVSXm8rIAbZo7jw7osbPNbphhcApy2IdxyVeSGblf1WtQlQ8dWGhVI38jJ0aY=,iv:NPkHA2zedPOuy8iOFC24Wb48edk4N6YhyJWL+A0Q+/k=,tag:ro3G18Ruhf2HOAigrUYMyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
